# Generated by Django 6.0.5 on 2026-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='correo_destino',
            field=models.EmailField(default='asistentecontable@bioingredientscr.com', help_text='Correo destino para el reenvío de facturas', max_length=254),
        ),
    ]
