# Generated by Django 6.0.5 on 2026-05-21 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_configuracionsistema_correo_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={},
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='usuario_web',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario_web',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='correo_destino',
            field=models.EmailField(default='asistentecontable@bioingredientscr.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='meses_historial',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CuentaCorreoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('correo_origen', models.EmailField(help_text='Correo de Gmail/Office365 del cliente', max_length=254)),
                ('password_aplicacion', models.CharField(max_length=200)),
                ('usuario_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
