# Generated by Django 6.0.5 on 2026-05-21 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_alter_configuracionsistema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cuenta_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturas.cuentacorreocliente'),
        ),
    ]
