# Generated by Django 6.0.5 on 2026-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(max_length=10)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('mensaje_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
