# Generated by Django 6.0.5 on 2026-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='detalles_json',
            field=models.TextField(default='[]'),
        ),
    ]
